/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package descriptor;

/**
 *
 * @author prayt
 */
import javax.swing.*;
import javax.swing.table.*;
import java.awt.event.*;
import java.io.*;
import java.util.StringTokenizer;

public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
  //JButton btnImportar, btnSalir;
  DefaultTableModel registro;
  static Lector lee=new Lector();
  static Relacional consulta=new Relacional();
 // JTable tabla;
  File archivo;
  FileReader fr;
  BufferedReader bw;
  String[][] matrizTabla;
  
    public Interfaz() {
         initComponents();
   // setLayout(null);
   // registro=(DefaultTableModel)TablaInf.getModel();
    //registro=new DefaultTableModel();
  //  registro.addColumn ("Nombre");
    //registro.addColumn("Genero");
   // registro.addColumn("Edad");
    //registro.addColumn("Fecha");
    //tabla=new JTable(registro);
    //TablaInf=new JTable(registro);
    //JScrollPane scroll=new JScrollPane(tabla);
    //tabla.setBounds(250,20,250,500);
    //scroll.setBounds(250, 20,250,500);
    //add(scroll);
    //btnImportar=new JButton("Importar");
    //btnImportar.setBounds (100, 50, 100, 30);
    //btnImportar.addActionListener(this);
    //add(btnImportar);
    //btnSalir=new JButton("Salir");
    //btnSalir.setBounds (100,600,100,30);
   // btnSalir.addActionListener(this);
   // add(btnSalir);
   // setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
   
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Consulta = new javax.swing.JButton();
        IngresoQuery = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Consulta1 = new javax.swing.JButton();
        Consulta2 = new javax.swing.JButton();
        Consulta3 = new javax.swing.JButton();
        BotonProd = new javax.swing.JButton();
        BotonT2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 153, 255));

        Consulta.setText("Query");
        Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaActionPerformed(evt);
            }
        });

        IngresoQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoQueryActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        Consulta1.setText("Tabla1");
        Consulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta1ActionPerformed(evt);
            }
        });

        Consulta2.setText("Seleccion");
        Consulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta2ActionPerformed(evt);
            }
        });

        Consulta3.setText("Proyeccion");
        Consulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta3ActionPerformed(evt);
            }
        });

        BotonProd.setText("Producto Car");
        BotonProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProdActionPerformed(evt);
            }
        });

        BotonT2.setText("Tabla2");
        BotonT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonT2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                    .addComponent(IngresoQuery))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Consulta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Consulta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Consulta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresoQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Consulta))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(Consulta1)
                        .addGap(4, 4, 4)
                        .addComponent(BotonT2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Consulta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Consulta3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonProd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresoQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoQueryActionPerformed
        // TODO add your handling code here:
        IngresoQuery.getText();
    }//GEN-LAST:event_IngresoQueryActionPerformed

    private void ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaActionPerformed
        // TODO add your handling code here:
         
        
        String a;
        a = IngresoQuery.getText();
        Query dos = new Query(a);
        
        for(int i=0;i<lee.tablas.size();i++){
           //lee.tablas.get(i);
            consulta.AddTabla(lee.tablas.get(i));
        }
        
        Tabla resultado=consulta.Opera(dos);
        resultado.muestraCont();
        jTextArea1.setText(resultado.muestraCont());
        /* for (int i = 0; i <resultado.N; i++){
            for(int j=0;j<resultado.M;j++){
               // System.out.print("["+tabla[i][j]+"]"); 
                
            }
           jTextArea1.setText("\n");
        }*/
        
        /*for (int i = 0; i < dos.SELECT.size(); i++){
            System.out.println("SELECT ELEMENTOS: " + dos.SELECT.get(i));
        }
        for (int i = 0; i < dos.DISTINCT.size(); i++){
            System.out.println("DISTINCT ELEMENTOS: " + dos.DISTINCT.get(i));
        }
        for (int i = 0; i < dos.FROM.size(); i++){
            System.out.println("FROM ELEMENTOS: " + dos.FROM.get(i));
        }
        //System.out.println(dos.FROM.get(0));
        for (int i = 0; i < dos.WHERE.size(); i++){
            System.out.println("WHERE ELEMENTOS: " + dos.WHERE.get(i));
        }
        System.out.println("----");*/
       
    }//GEN-LAST:event_ConsultaActionPerformed

    private void Consulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta1ActionPerformed
        // TODO add your handling code here:
              String a;
        a = IngresoQuery.getText();
        Query dos = new Query(a);
        
        for(int i=0;i<lee.tablas.size();i++){
           //lee.tablas.get(i);
            consulta.AddTabla(lee.tablas.get(i));
        }
        
        Tabla resultado=consulta.AsignaTabla(dos,0);
        resultado.muestraCont();
        jTextArea1.setText(resultado.muestraCont());
        /* for (int i = 0; i <resultado.N; i++){
            for(int j=0;j<resultado.M;j++){
               // System.out.print("["+tabla[i][j]+"]"); 
                
            }
           jTextArea1.setText("\n");
        }*/
        
        /*for (int i = 0; i < dos.SELECT.size(); i++){
            System.out.println("SELECT ELEMENTOS: " + dos.SELECT.get(i));
        }
        for (int i = 0; i < dos.DISTINCT.size(); i++){
            System.out.println("DISTINCT ELEMENTOS: " + dos.DISTINCT.get(i));
        }
        for (int i = 0; i < dos.FROM.size(); i++){
            System.out.println("FROM ELEMENTOS: " + dos.FROM.get(i));
        }
        //System.out.println(dos.FROM.get(0));
        for (int i = 0; i < dos.WHERE.size(); i++){
            System.out.println("WHERE ELEMENTOS: " + dos.WHERE.get(i));
        }
        System.out.println("----");*/
    }//GEN-LAST:event_Consulta1ActionPerformed

    private void Consulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta2ActionPerformed
        // TODO add your handling code here:
          String a;
        a = IngresoQuery.getText();
        Query dos = new Query(a);
        //dos.SELECT.clear();
        //dos.activos[3]=-1;
        //dos.SELECT.add("*");
        for(int i=0;i<lee.tablas.size();i++){
           //lee.tablas.get(i);
            consulta.AddTabla(lee.tablas.get(i));
        }
        consulta.Opera(dos);
        Tabla resultado= consulta.SELECCION;
        resultado.muestraCont();
        jTextArea1.setText(resultado.muestraCont());
     /* for (int i = 0; i < dos.SELECT.size(); i++){
            System.out.println("SELECT ELEMENTOS: " + dos.SELECT.get(i));
        }
      //   for (int i = 0; i < dos.DISTINCT.size(); i++){
        //     System.out.println("DISTINCT ELEMENTOS: " + dos.DISTINCT.get(i));
     //    }
        for (int i = 0; i < dos.FROM.size(); i++){
            System.out.println("FROM ELEMENTOS: " + dos.FROM.get(i));
        }
        //System.out.println(dos.FROM.get(0));
        for (int i = 0; i < dos.WHERE.size(); i++){
            System.out.println("WHERE ELEMENTOS: " + dos.WHERE.get(i));
        }*/
    }//GEN-LAST:event_Consulta2ActionPerformed

    private void Consulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta3ActionPerformed
       String a;
        a = IngresoQuery.getText();
        Query dos = new Query(a);
        
        for(int i=0;i<lee.tablas.size();i++){
           //lee.tablas.get(i);
            consulta.AddTabla(lee.tablas.get(i));
        }
        
        Tabla resultado=consulta.Opera(dos);
        resultado.muestraCont();
        jTextArea1.setText(resultado.muestraCont());
        /* for (int i = 0; i <resultado.N; i++){
            for(int j=0;j<resultado.M;j++){
               // System.out.print("["+tabla[i][j]+"]"); 
                
            }
           jTextArea1.setText("\n");
        }*/
        
        /*for (int i = 0; i < dos.SELECT.size(); i++){
            System.out.println("SELECT ELEMENTOS: " + dos.SELECT.get(i));
        }
        for (int i = 0; i < dos.DISTINCT.size(); i++){
            System.out.println("DISTINCT ELEMENTOS: " + dos.DISTINCT.get(i));
        }
        for (int i = 0; i < dos.FROM.size(); i++){
            System.out.println("FROM ELEMENTOS: " + dos.FROM.get(i));
        }
        //System.out.println(dos.FROM.get(0));
        for (int i = 0; i < dos.WHERE.size(); i++){
            System.out.println("WHERE ELEMENTOS: " + dos.WHERE.get(i));
        }
        System.out.println("----");*/
    }//GEN-LAST:event_Consulta3ActionPerformed

    private void BotonProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProdActionPerformed
        // TODO add your handling code here:
          String a;
        a = IngresoQuery.getText();
        Query dos = new Query(a);
        //dos.SELECT.clear();
        //dos.activos[3]=-1;
        //dos.SELECT.add("*");
        for(int i=0;i<lee.tablas.size();i++){
           //lee.tablas.get(i);
            consulta.AddTabla(lee.tablas.get(i));
        }
       // consulta.productoCartesiano();
        //Tabla resultado= consulta.SELECCION;
       // resultado.muestraCont();
        jTextArea1.setText(consulta.resProd);
  /*    for (int i = 0; i < dos.SELECT.size(); i++){
            System.out.println("SELECT ELEMENTOS: " + dos.SELECT.get(i));
        }*/
      //   for (int i = 0; i < dos.DISTINCT.size(); i++){
        //     System.out.println("DISTINCT ELEMENTOS: " + dos.DISTINCT.get(i));
     //    }
      /*  for (int i = 0; i < dos.FROM.size(); i++){
            System.out.println("FROM ELEMENTOS: " + dos.FROM.get(i));
        }
        //System.out.println(dos.FROM.get(0));
        for (int i = 0; i < dos.WHERE.size(); i++){
            System.out.println("WHERE ELEMENTOS: " + dos.WHERE.get(i));
        }*/
    }//GEN-LAST:event_BotonProdActionPerformed

    private void BotonT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonT2ActionPerformed
        // TODO add your handling code here:
         String a;
        a = IngresoQuery.getText();
        Query dos = new Query(a);
        
        for(int i=0;i<lee.tablas.size();i++){
           //lee.tablas.get(i);
            consulta.AddTabla(lee.tablas.get(i));
        }
        
        Tabla resultado=consulta.AsignaTabla(dos,1);
        resultado.muestraCont();
        jTextArea1.setText(resultado.muestraCont());
    }//GEN-LAST:event_BotonT2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
               
            }
        });
        
        lee.cargarTablas();
       
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonProd;
    private javax.swing.JButton BotonT2;
    public javax.swing.JButton Consulta;
    public javax.swing.JButton Consulta1;
    public javax.swing.JButton Consulta2;
    public javax.swing.JButton Consulta3;
    private javax.swing.JTextField IngresoQuery;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
